version: '3.1'

services:
  # Если хотите подключить базу данных
  db:
    # ВНИМАТЕЛЬНО! ВОТ ЭТО НАЗВАНИЕ СЕРВИСА - db - ДОЛЖНО БЫТЬ УКАЗАНО В БОТЕ КАК host В ПОДКЛЮЧЕНИИ К БАЗЕ ИЗ БОТА
    # ТО ЕСТЬ НЕ АЙПИШНИК И НЕ ЛОКАЛХОСТ, А db
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    container_name: "quiz-bot-redis"
    image: redis:6.0-alpine
    hostname: redis
    restart: always
    networks:
      - botnet
    volumes:
      - "redis_config:/usr/local/etc/redis"
      - "redis_data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  tgbot:
    container_name: lt_quiz_bot
    build:
      context: .
    command: python -m app
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    volumes:
      - .:/src
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
    # Бот стартует после запуска базы
    depends_on:
      - db
      - redis

# указываются используемые сети
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge

volumes:
    redis_config:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './redis-config'
    redis_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './redis-data'